// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindowConfigurator.Data;

#nullable disable

namespace WindowConfigurator.Data.Migrations
{
    [DbContext(typeof(WindowConfiguratorDbContext))]
    partial class WindowConfiguratorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("WindowConfigurator.Data.Entities.ConfiguredWindowItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AuthoritativePrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FrameHeightDecimal")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FrameWidthDecimal")
                        .HasColumnType("TEXT");

                    b.Property<int>("LineItemNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MeetsEgress")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("OutsideMeasureHeightDecimal")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OutsideMeasureWidthDecimal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PricingComputedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductLineKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuoteSessionId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RoughOpeningHeightDecimal")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RoughOpeningWidthDecimal")
                        .HasColumnType("TEXT");

                    b.Property<int>("SectionCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuoteSessionId");

                    b.ToTable("ConfiguredWindowItems");
                });

            modelBuilder.Entity("WindowConfigurator.Data.Entities.QuoteSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultProductLineKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MagicLinkExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MagicLinkToken")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("QuoteSessions");
                });

            modelBuilder.Entity("WindowConfigurator.Data.Entities.TenantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedProductLineKeys")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MixedProductLinesAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookCallbackUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("WindowConfigurator.Data.Entities.ConfiguredWindowItemEntity", b =>
                {
                    b.HasOne("WindowConfigurator.Data.Entities.QuoteSessionEntity", null)
                        .WithMany("Items")
                        .HasForeignKey("QuoteSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WindowConfigurator.Data.Entities.QuoteSessionEntity", b =>
                {
                    b.HasOne("WindowConfigurator.Data.Entities.TenantEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WindowConfigurator.Data.Entities.TenantEntity", b =>
                {
                    b.OwnsOne("WindowConfigurator.Data.Entities.TenantBrandingConfig", "Branding", b1 =>
                        {
                            b1.Property<Guid>("TenantEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AccentColor")
                                .HasColumnType("TEXT");

                            b1.Property<string>("LogoUrl")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PrimaryColor")
                                .HasColumnType("TEXT");

                            b1.HasKey("TenantEntityId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantEntityId");
                        });

                    b.Navigation("Branding")
                        .IsRequired();
                });

            modelBuilder.Entity("WindowConfigurator.Data.Entities.QuoteSessionEntity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
